### ISSUE TITLE
Opening in VS2015

### ISSUE THREAD

**Issue by johnnyontheweb** [quamotion/remoteviewing#17]
Dear all,
I recentrly updated my local copy of the source code, and I'm not able to open the solution in vs2015. I get the following error (sorry it is in Italian, I tried to translate it in English below):

```
 lo spazio dei nomi XML predefinito del progetto deve essere lo spazio dei nomi XML di MSBuild. Se il progetto viene modificato nel formato MSBuild 2003, aggiungere xmlns="http://schemas.microsoft.com/developer/msbuild/2003" all'elemento <Project>. Se il progetto è stato modificato nel formato precedente 1.0 o 1.2, convertilo al formato MSBuild 2003. 

TRANSLATION:
The predefined XML namespace must be the MSBuild XML namespace. If the project is modified into MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> item. If the project has been modified from the previous formats 1.0 or 1.2, convert it to MSBuild 2003 format.
```

Can you help? In which version of VS are you working?

**Comment by qmfrederik** [comment]
Hi @johnnyontheweb 

Yeah, everything got upgraded to the new .NET Core project format, so you'd need at least Visual Studio 2017 for that.

**Comment by johnnyontheweb** [comment]
So any chance to get it to work without that? Can be the projects be downgraded or not?

**Comment by qmfrederik** [comment]
If you just want to compile, you can download the .NET Core SDK and just build using `dotnet build`.

I don't think there's an automated way to downgrade solution files, but you can just create a new .csproj file using Visual Studio 2017 and add all the original source files to that new project. So you would have two .csprojs side by side - one for VS2017/.NET Core, and one for VS2015.

**Comment by qmfrederik** [comment]
I'm going to close this issue for now, as it's almost 3 years old and there's no plan to add support for VS2015.
