### ISSUE TITLE
Add support for ExtendedDesktopSize

### ISSUE THREAD

**Issue by kekekeks** [quamotion/remoteviewing#58]
It allows clients like noVNC to ask the server to change the resolution.

**Comment by qmfrederik** [comment]
I'd be happy to take a PR, the message is defined here: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#setdesktopsize

**Comment by qmfrederik** [comment]
@kekekeks I'm going to implement this in the coming days, at least at the protocol level.

If you're still interested in this, can you give me more info about your use case? Where is the frame buffer source coming from? Would you expect the frame buffer source to act on this, or would you expect the VNC server to resize the images instead?

**Comment by kekekeks** [comment]
> Where is the frame buffer source coming from

I have an experimental VNC backend for AvaloniaUI. Frames are coming from a UI control exported as VNC display, so I was planning to resize said control.

**Comment by kekekeks** [comment]
https://www.youtube.com/watch?v=HAyHIvSzweM
https://www.youtube.com/watch?v=8lnn5Tg8xTM

**Comment by qmfrederik** [comment]
So, in your case, you'd expect something like `VncFramebufferSource.Resize` which is invoked whenever the client requests a resize, right?

**Comment by kekekeks** [comment]
```cs
// Needed because server needs to announce the support for the extension
bool SupportsResize {get;}

// Resize request might fail to meet the control constraints and server is allowed to decline the request
bool ResizeRequested(int width, int height);
```
